### PR TITLE
Wbiesing/before genomix data refactor

### PR DESCRIPTION
**Pull request by jakebiesinger**
Hi @anbangx @JavierJia @Nan-Zhang

This branch is the latest master from hyracks, Yingyi's updates to remove in-place updates, and my additions to logging.  I will have to manually merge this but I wanted to put it here so you could get the notifications, etc.

### CODE REVIEW

**Comment by jakebiesinger** [comment]
BTW this build will fail because it needs incoming changes in one of @anbangx 's feature branch.

**Comment by jakebiesinger** [comment]
Actually, if you're all cool with it, I'm going to go ahead and merge it into our main branch via the "merge pull request" button here.  Can you give me a LGTM after looking over the commits I added?

**Comment by JavierJia** [comment]
LGTM

**Comment by anbangx** [comment]
LGTM

**Pull request merged**
