### PR TITLE
recover tests edge map for genomix-data

### PR DESCRIPTION
**Pull request by Nan-Zhang**
this branch just move from google code, now it is ready to push. @jakebiesinger  @JavierJia  @anbangx

### CODE REVIEW

**Comment by jakebiesinger** [comment]
@Nan-Zhang can you say at a high level what these changes are?  I don't understand what you mean by "recover tests edge map".  You mean you rewrote the tests and they pass now?

**Comment by Nan-Zhang** [comment]
@jakebiesinger this is just a old branch which I left it in the google code, this branch's function is to fix the tests in edgeMap which could be used to test our treeeMap based EdgeMap.

**Comment by jakebiesinger** [comment]
LGTM.  You'll have to merge with/rebase onto the main branch again since it has progressed since you submitted this PR.

**Comment by Nan-Zhang** [comment]
merged.

**Pull request merged**
