### PR TITLE
another :clap: for @Nan-Zhang! node offsets were wrong for flipped merges

### PR DESCRIPTION
**Pull request by jakebiesinger**
Good work, @Nan-Zhang!

@anbangx @JavierJia Do you want to see the pretty graphs we've produced?

### CODE REVIEW

**Comment by jakebiesinger** [comment]
@Nan-Zhang can you go ahead and fix #39 and push directly into this branch before we merge?  The names were the source of this logic error.

**Comment by JavierJia** [comment]
:+1:  please please leave the graph till tomorrow~, Let me enjoy it tomorrow ~

**Comment by anbangx** [comment]
Where is the pretty graph? I also want to enjoy.....

On Wed, Oct 23, 2013 at 7:16 PM, Jianfeng Jia notifications@github.comwrote:

> [image: :+1:] please please leave the graph till tomorrow~, Let me enjoy
> it tomorrow ~
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uci-cbcl/genomix/pull/38#issuecomment-26961973
> .

## 

Best Regards,

Anbang Xu

**Comment by jakebiesinger** [comment]
Here are three reads, with the top two paired.  They are broken into kmers and the first and last kmer of the top read are marked with a red ball. Several rounds of merging bring us to the last line, where a merge between the left two arrows will take place.The leftmost arrow will merge towards the middle arrow, causing it to flip.  



Where should the red ball end up?  Still on the left?  Or on the right, closer to the other red ball?

The answer is, it shouldn't move at all, even if the whole kmer flips.  Its distance must remain the same.  I had thought otherwise, and that was the source of the logic error corrected in this commit.

Can we merge?

**Comment by Nan-Zhang** [comment]
LGTM, it can be merged now.

**Comment by jakebiesinger** [comment]
Merging now.

**Pull request merged**
