### PR TITLE
Split file manager

### PR DESCRIPTION
**Pull request by JavierJia**
@Elmira88 I split the write to hdfs `FileManager` so that it an be used by storing the walk also. 
Please have a look

### CODE REVIEW

**Comment by JavierJia** [comment]
@jakebiesinger , want to have a look ? Or we can merge it ?

**Comment by jakebiesinger** [comment]
Sorry guys, what does the writewalk actually do?  This is to store the final walk that is generated?

**Comment by Elmira88** [comment]
@jakebiesinger  yes. 
@JavierJia Sorry! I got busy with other parts, I completely forgot about this.

**Comment by JavierJia** [comment]
@jakebiesinger  I just split the File manager, so all the other class could see this singleton manager and create the File for any class. So if the you want use this FM to manage the walker file, it will be OK to do. Leave the msg to me if you met any problems.

**Comment by jakebiesinger** [comment]
LGTM.  I just merged a bunch of other stuff into genomix/fullstack_genomix and it looks like the commit graph is wonky now (it's merging 60 commits into your branch rather than merging a few commits from you branch into fullstack)

**Comment by jakebiesinger** [comment]
So this merged into your branch, yo.  Meaning it's not in fullstack?

**Comment by JavierJia** [comment]
Oh, I close it ? Let me merge it.

**Comment by JavierJia** [comment]
But it seems already merged. We can use it  now

**Comment by jakebiesinger** [comment]
You might have to send another PR that merges your branch into the main
one.  I don't know how it got confused.

## 

Jake Biesinger
Graduate Student
Xie Lab, UC Irvine

**Comment by jakebiesinger** [comment]
It's not in the main branch though afaict.  Do you see you commits in the
main branch history?

## 

Jake Biesinger
Graduate Student
Xie Lab, UC Irvine

**Pull request merged**
